project:
  type: book

book:
  title: "TimeSeriesAnalysis"
  author: "Castor"
  date: "11/4/2024"
  chapters:
    - index.qmd
    - Ch1/1-金融数据及其特征.qmd
    - Ch2/2-线性时间序列模型.qmd
    - Ch3/3-自回归模型.qmd
    - Ch4/4-移动平均模型.qmd
    - Ch5/5-ARMA模型.qmd

format:
  html:
    theme: 
      light: flatly
      dark: slate
    code-fold: true
  pdf:
    documentclass: book
    mainfont: SimHei

resources:
  - CNAME
