# 线性时间序列模型

## 介绍

课程采用蔡瑞胸（Ruey S. Tsay）的《金融数据分析导论：基于R语言》([Tsay 2013](https://www.math.pku.edu.cn/teachers/lidf/course/fts/ftsnotes/html/_ftsnotes/fts-tslin.html#ref-Tsay13:IAFD)) （An Introduction to Analysis of Financial Data with R）作为主要教材之一。 “线性时间序列模型”这一部分是教材的第二章和第三章的授课笔记， 本章讲授时间序列的线性模型，包括：

-   一些基本概念
-   AR, MA, ARMA模型
-   单位根过程
-   指数平滑
-   季节模型
-   回归模型中误差项有序列相关的处理
-   长记忆的分数阶差分模型
-   模型比较
-   实例分析

### 例子：可口可乐公司盈利数据

序列仍体现出缓慢的、非单调的上升趋势，又有明显的每年的周期变化（称为季节性）， 还有短期的波动：

```{python}
{{< include _sample_cola_1.py >}}
{{< include _sample_cola_2.py >}}
```

标出不同季节的数据点，可以看出，每年一般冬季和春季最低， 夏季最高，秋季介于夏季和冬季之间：

```{python}
{{< include _sample_cola_1.py >}}
{{< include _sample_cola_3.py >}}
```

### 例子：标普500指数月对数收益率

收益率在0上下波动，除了个别时候基本在某个波动范围之内：

```{python}
{{< include _sample_sp_1.py >}}
{{< include _sample_sp_2.py >}}
```

## 平稳性

[例子：标普500指数月对数收益率]所展示的收益率曲线基本呈现一个在水平线（一般是 0）上下波动，且波动范围基本不变，这样的表现是时间序列【弱平稳序列】的表现。

[例子：可口可乐公司盈利数据]所展示的价格曲线呈现出水平的上下起伏，如果分成几段的话，各段的平均值差距较大，这表现出拍【非平稳】的特性。

**时间序列**：设有随机变量序列 $\{x_t,t=\ldots,-2,-1,0,1,2,\ldots\}$,称其为一个时间序列。其中$x_t$是一个随机变量，也可以写成大写的$X_t$。时间序列$\{X_t\}$严格来说是一个二元的函数 $X(t,\omega),t\in\mathbb{Z}(\mathbb{Z}$表示所有整数组成的集合), $\omega \in \Omega$, $\Omega$表示在一定的条件下所有可能的试验结果的集合。经济和金融中的时间序列我们只能观察到其中某一个$\omega_0\in\Omega$对应的结果，称为一条“轨道”。而针对随机变量的许多理论性质都是在$\omega\in\Omega$上讨论的，比如$EX_t=\int X_t(\omega)P(d\omega)$是$X_t(\omega)$对$\omega\in\Omega$的平均。

为了能够用一条轨道的观测样本得到所有$\omega\in\Omega$的性质，需要时间序列满足“遍历性”。

时间序列的样本：设$\{x_t,t=1,2,\ldots,T\}$是时间序列中的一段。仍将$x_t$看成随机变量，也可以写成大写
的$X_t$。如果有了具体数值，那么样本就是一条轨道中的一段。

**自协方差函数**：时间序列$\{X_t\}$中两个随机变量的协方差 $Cov(X_s,X_t)$叫做自协方差。如果
$Cov(X_s,X_t)=\gamma_{|t-s|}$仅依赖于$t-s$,则称
$$\gamma_k=\mathrm{Cov}(X_{t-k},X_t),k=0,1,2,\ldots $$

为时间序列$\{X_t\}$的自协方差函数。因为Cov$( X_s, X_t) =$Cov$( X_t, X_s)$, 所以$\gamma_{-k}=\gamma_k$。易见
$\gamma_0=\mathrm{Var}(X_t)$。

由Cauchy-Schwartz不等式：
$$|\gamma_k|=|E[(X_{t-k}-\mu)(X_t-\mu)]|\leq\left(E(X_{t-k}-\mu)^2\:E(X_t-\mu)^2\right)^{1/2}=\gamma_0$$

**弱平稳序列**(宽平稳序列，weakly stationary time series): 如果时间序列$\{X_t\}$存在有限的二阶矩且满足：

1. $EX_t= \mu$与$t$无关；
2. $\mathrm{Var}(X_t)=\gamma_0$与$t$无关；
3. $\gamma _{k}=$Cov$( X_t- k, X_{t})$, $k= 1, 2, \ldots$与$t$无关，

则称$\{X_t\}$为弱平稳序列。

适当条件下可以用时间序列的样本估计自协方差函数，这是用一条轨道的信息推断所有实验结果$\Omega$,估计公
式为：
$$\hat{\gamma}_k=\frac{1}{T}\sum_{t=k+1}^T(x_{t-k}-\bar{x})(x_t-\bar{x}),k=0,1,\ldots,T-1$$

称$\hat{\gamma}_k$为样本自协方差。 注意这里用了$1/T$而不是$1/(T-k)$,用$1/(T-k)$在获得无偏性的同时会造成一
些理论上的困难。

## 相关系数和自相关系数
### 相关系数

```{python}
{{< include _sample_sp_1.py >}}
{{< include _sample_sp_3.py >}}
```

上图是IBM股票月度简单收益率对标普500收益率的散点图，可以看出两者有明显的正向相关关系。

两个随机变量$X$和$Y$的相关系数定义为：

$$\rho(X,Y)=\rho_{xy}=\dfrac{\mathrm{Cov}(X,Y)}{\sqrt{\mathrm{Var}(X)\mathrm{Var}(Y)}}=\dfrac{E[(X-\mu_x)(Y-\mu_y)]}{\sqrt{E(X-\mu_x)^2E(Y-\mu_y)^2}}$$

如果有$(X,Y)$的独立同分布样本$( x_t, y_t)$, $t= 1, 2, \ldots , T$, 可估计相关系数（皮尔逊，Pearson）为：

$$\hat{\rho}_{xy}=\frac{\sum_{t=1}^T(x_t-\bar{x})(y_t-\bar{y})}{\sqrt{\sum_{t=1}^T(x_t-\bar{x})^2\sum_{t=1}^T(y_t-\bar{y})^2}}$$

对于不独立的样本，比如时间序列样本，也可以计算相关系数，其估计合理性需要一些模型假设。
对于联合分布非正态的情况，有时相关系数不能很好地反映$X$和$Y$的正向或者负向的相关。 斯皮尔曼
(Spearman) 相关系数是计算$X$的样本的秩(名次)与$Y$的样本的秩之间的相关系数，也称为Spearmam
rank correlation。

另一种常用的非参数相关系数是肯德尔tau(Kendall's $\tau)$系数，反映了一致数对和非一致数对之间的差别。
对随机向量$(X,Y)$,设$(X_1,Y_1),(X_2,Y_2)$相互独立且联合分布与$(X,Y)$联合分布相同，定义$X$和$Y$的肯
德尔tau系数为：

$$\tau=P\left[(X_1-X_2)(Y_1-Y_2)>0\right]-P\left[(X_1-X_2)(Y_1-Y_2)<0\right]$$

即两个观测的分量次序一致的概率减去分量次序相反的概率。一致的概率越大，说明两个的正向相关性越
强。

对 IBM 收益率与标普收益率数据计算这三种相关系数：

```{python}
{{< include _sample_sp_1.py >}}
{{< include _sample_sp_4.py >}}
```

### 自相关函数与白噪声

设$\{X_t\}$为弱平稳序列，$\{\gamma_k\}$为自协方差函数。则

$$\rho(X_{t-k},X_t)=\frac{\operatorname{Cov}(X_{t-k},X_t)}{\sqrt{\operatorname{Var}(X_{t-k})\operatorname{Var}(X_t)}}=\frac{\gamma_k}{\sqrt{\gamma_0\gamma_0}}=\frac{\gamma_k}{\gamma_0},\:k=0,1,\ldots,\:\forall t$$

记$\rho_k=\gamma_k/\gamma_0$, 这是$X_t-k$与$X_t$的相关系数且与$t$无关，称$\{\rho_k,k=0,1,\ldots\}$为时间序列$\{X_t\}$的自相关函数 (Autocorrelation function, ACF)。$\rho_0=1$。

如果弱平稳序列$\{X_t\}$满足$\rho_k=0,k=1,2,\ldots$, 称$\{X_t\}$为**白噪声序列**。如果随机变量序列$\{X_t\}$独立且期望和方差不随时间而变，则$\{X_t\}$是白噪声序列，称为独立白噪声。如果独立白噪声还是同分布的，称为独立同分布白噪声。

适当条件下$\rho_k$可以从时间序列样本估计为：

$$\hat{\rho}_k=\frac{\hat{\gamma}_k}{\hat{\gamma}_0},\:k=0,1,\ldots $$

$\hat{\rho}_0=1$。称$\hat{\rho}_k,k=1,2,\ldots$为**样本自相关函数**。

如果时间序列严平稳遍历，则$\hat{\rho}_k$是$\rho_k$的强相合估计。

若$\{X_t\}$为有二阶矩的独立同分布随机变量列，则 $\hat{\rho}_k(k>0)$渐近服从N$(0,\frac1T)$。

如果$\{\varepsilon_t\}$是零均值独立同分布白噪声，$q$为非负整数，$\{\psi_j,j=0,1,\ldots,q\}$是数列，$\psi_0=1$,
$$X_t=\mu+\sum_{j=0}^q\psi_j\varepsilon_{t-j},\:t\in\mathbb{Z},$$

则从$\{X_t,t=1,\ldots,T\}$计算的ACF满足：当$k>q$时，$\sqrt T\hat{\rho}_k$渐近服从$\mathbb{N}(0,1+2\sum_{j=0}^q\rho_j^2)$,这称为Bartlett公式。

#### 例子：CRSP 的第10分位组合的月度收益率

第10分位组合是NYSE、AMEX、NASDAQ市值最小的10%股票组成的投资组合， 每年都重新调整。

-   CRSP是Center for Research in Security Prices, 位于Chicago Booth。
-   NYSE(The New York Stock Exchange, 纽约证券交易所),
-   AMEX(American Stock Exchange, 美国证券交易所，在纽约华尔街附近)，
-   NASDAQ(National Association of Securities Dealers Automated Quotations，纳斯达克，位于纽约)。

```{python}
{{< include _sample_d10_1.py >}}
{{< include _sample_d10_2.py >}}
```

绘制时间序列的自相关函数图（ACF）：

```{python}
{{< include _sample_d10_1.py >}}
{{< include _sample_d10_3.py >}}
```

在 ACF 图像中，Lag 相当于 $k$，ACF 相当于 $\hat{\rho}_k$。

ACF 图中横轴上下两条水平下是在独立同分布白噪声假设下的加减两倍标准差，即 $\pm\frac2{\sqrt{T}}$。如果独立同分布白噪声假设成立，每个 $\hat{\rho}_k$ 有 95% 以上的概率落入这两条线之间。

ACF 图 $k=0$ 处总对应 $\hat{\rho}_0=1$。

上图的 $\hat{\rho}_1$ 和 $\hat{\rho}_{12}$ 都超出了界限(因为是月度数目，横轴的单位是1/12为一个时间点)。从此图可以认为此投资组合的收益率不是白噪声。

### 用单个自相关系数作白噪声检验

如果$\{X_t\}$是独立同分布白噪声，则 $\hat{\rho}_k(k\geq 1)$ 近似 $N(0,1/T)$。若 $H_0$ 是序列为白噪声，取统计量：

$$t = \sqrt{T}\hat{\rho}_k$$

如果$|t|>$qnorm$(1-\alpha/2)$，则拒绝白噪声零假设。实际中常取$\alpha=0.05$, qnorm$(1-\alpha/2)\approx2$,当$\hat{\rho}_1$超出$\pm2/\sqrt T$则拒绝$H_0$,有多个$\hat{\rho}_k$超出$\pm2/\sqrt T$也可拒绝$H_0$,有一个$t$统计量值很大(比如超出$\pm3$)也可拒绝$H_0$。

在判断$\{X_t\}$是否$X_t=\mu+\sum_{j=0}^q\psi_j\varepsilon_{t-j}$这样的模型时，根据 Bartlet 公式，可取：

$$t=\frac{\hat{\rho}_k}{\sqrt{\frac{1}{T}\left(1+2\sum_{j=1}^{k-1}\hat{\rho}_j^2\right)}},\:k>q$$

当$t$超出 qnorm$(1-\alpha/2)$时拒绝这样的模型。

#### TODO：例子 3.3

### Ljung-Box 白噪声检验

为了检验时间序列样本是否来自白噪声序列，可以检验 $\rho_k = 0, k = 1, 2, \cdots$ 的零假设。前面检验单个 $\rho_k$ 的做法如果正对多个进行检验就有多重检验的第一类错误增大的问题。

Box 和 Pierce(G. Box & Pierce, 1970) 提出了混成统计量 (Portmanteau statistic)：
$$Q_*(m)=T\sum_{j=1}^m\hat{\rho}_j^2$$

用来检验：

$$H_0:\rho_1=\cdots=\rho_m=0\longleftrightarrow H_a: \text{不全为零}$$

在$\{X_t\}$是独立白噪声序列条件下，$Q_*(m)$近似服从$\chi^2(m)$分布。给定检验水平$\alpha$,当$Q_*(m)>$qchisq$(1-\alpha,m)$ 时拒绝$H_{0}$,否定白噪声假设。如果检验的序列是线性时间序列估计的残差序列，则卡方自由度应改为$m$减去估计的系数个数。

Ljung 和 Box(Ljung & Box, 1978) 对此检验方法进行了改进。统计量改为：

$$Q(m)=T(T+2)\sum_{j=1}^m\frac{\hat{\rho}_j^2}{T-j}$$

在独立同分布白噪声假设下仍近似服从$\chi^2(m)$分布。当$Q( m) >$qchisq$( 1- \alpha , m)$时拒绝$H_0$,否定白噪声假设。这个检验称为 Ljung-Box 白噪声检验。如果检验的序列是线性时间序列估计的残差序列，则卡方自由度应改为$m$减去估计的系数个数。比如，对 ARMA$(p,q)$模型建模的残差作白噪声检验，卡方自由度应改为$m-(p+q)$。

#### 例子：检验 IBM 股票月收益率是否为白噪声

绘制数据的 ACF 图像：

```{python}
{{< include _sample_ibm_1.py >}}
{{< include _sample_ibm_2.py >}}
```

从 ACF 图来看，月度收益率是白噪声。

作 Ljung-Box 白噪声检验，分别取 $m = 12$ 和 $m = 24$：

```{python}
{{< include _sample_ibm_1.py >}}
{{< include _sample_ibm_3.py >}}
```

可以看出，在 0.05 水平下均不拒绝零假设，支持 IBM 月度简单收益率是白噪声的零假设。

从简单收益率计算对数收益率，并进行 LB 白噪声检验：

```{python}
{{< include _sample_ibm_1.py >}}
{{< include _sample_ibm_4.py >}}
```

可以看出，在 0.05 水平下不拒绝零假设。

#### 例子：检验 CRSP 的第10分位组合的月度收益率是否为白噪声

这是 [例子：CRSP 的第10分位组合的月对数收益率] 的继续，对其数据作白噪声检验。

```{python}
{{< include _sample_d10_1.py >}}
{{< include _sample_d10_4.py >}}
```

可以看出，在 0.05 水平下拒绝零假设，认为 CRSP 第10分位组合的月度简单收益率不是白噪声。

有效市场假设认为收益率是不可预测的，也就不会有非零的自相关。但是，股价的决定方式和指数收盗率的计算方式等可能会导致在观测到的收益率序列中有自相关性。高频金融数据中很常见自相关性。

常见的白噪声检验还有 TREVOR S. BREUSCH (1978) 和 LESLIE G. GODFREY (1978) 提出的拉格朗日乘子法检验(LM 检验)。零假设为白噪声，对立假设为 AR、MA 或者 ARMA。

## 线性时间序列

设$\{X_t\}$是独立同分布的二阶矩有限的随机变量，称$\{X_t\}$为**独立同分布白噪声** (white noise)。最常用的白噪声一般假设均值为零。如果$\{X_t\}$独立同 N$(0,\sigma^2)$分布，称$\{X_t\}$为高斯(Gaussian) 白噪声或正态白噪声。

白噪声序列的自相关函数为零($\rho_0=1$除外)。

实际应用中如果样本自相关函数近似为零(ACF 图中都位于控制线之内或基本不超出控制线),则可认为该序列是白
噪声的样本。

设$\{\varepsilon_t\}$是零均值独立同分布白噪声，$\operatorname{Var}(\varepsilon_t)=\sigma^2$,数列$\{\psi_j\}$满足$\sum_j\psi_j^2<\infty,\psi_0=1$,令：

$$X_t=\mu+\sum_{j=0}^\infty\psi_j\varepsilon_{t-j},t\in\mathbb{Z}$$

则称$\left\{X_t\right\}$是(因果)线性时间序列，$\varepsilon_t$代表了在时刻$t$增加的变动信息，称为**新息**(innovation)或者扰动 (shock)。因果线性时间序列满足新息$\varepsilon_{t+j}(j\geq1)$与历史的$X_t,X_{t-1}$独立。而且，$\{X_t-1,X_{t-2},...\}$与$\{\varepsilon_t-1,\varepsilon_{t-2},...\}$可以互相线性地表示。

这个定义可以放宽到$\left\{\varepsilon_t\right\}$是宽平稳的不相关列(宽白噪声)的情形。这时，称(3.1)为$\left\{X_t\right\}$的 **Wold 分解**，称$\left\{X_t\right\}$
为**纯非决定性序列**。

许多弱平稳时间序列是线性时间序列，后面讲到的 AR 模型、MA 模型、ARMA 模型都属于线性时间序列。另外的
许多弱平稳时间序列可以被线性时间序列近似。非平稳的时间序列不是线性时间序列。

$\{\psi_j\}$称为模型的$\psi$权重。易见：

$$EX_t=\mu,\quad\mathrm{Var}(X_t)=\sigma^2\sum_{j=0}^\infty\psi_j^2,$$

自协方差函数为：

$$\begin{aligned}\gamma_{k}=&\mathrm{Cov}(X_{t},X_{t-k})=E\left[\left(\sum_{i=0}^{\infty}\psi_{i}\varepsilon_{t-i}\right)\left(\sum_{i=0}^{\infty}\psi_{i}\varepsilon_{t-i-l}\right)\right]\\=&E\left(\sum_{i,j=0}^{\infty}\psi_{i}\psi_{j}\varepsilon_{t-i}\varepsilon_{t-j-k}\right)=\sigma^{2}\sum_{i,j=0}^{\infty}\psi_{i}\psi_{j}\delta_{i-j-k}\\=&\sigma^{2}\sum_{j=0}^{\infty}\psi_{j}\psi_{j+k}\end{aligned}$$

其中$\delta_k$当$k=0$时为 1,当$k\neq0$时为0。

自相关函数为：

$$\rho_k=\dfrac{\gamma_k}{\gamma_0}=\dfrac{\sum_{j=0}^\infty\psi_j\psi_{j+k}}{1+\sum_{j=1}^\infty\psi_j^2},\:k\ge0$$

线性时间序列模型满足$\psi_j\to0,j\to\infty$,所以历史上的扰动的影响会逐渐消失。另外$\rho_k\to0,k\to\infty$,所以相距较远的观测之间的相关性很小。

不是所有的弱平稳时间序列都有这样的性质。非平稳序列更是不需要满足这些性质。

## 附录：补充知识
