# 自回归模型
## 自回归模型的概念

如果$\rho_1\neq0$,则$X_t$与$X_{t-1}$相关，可以用$X_{t-1}$预测$X_t$。最简单的预测为线性组合，如下模型：

$$X_t=\phi_0+\phi_1X_{t-1}+\varepsilon_t$$

称为一阶自回归模型 (Autoregression model),记作 AR(1)模型。其中$\{\varepsilon_t\}$是零均值独立同分布白噪声序列，方差为$\sigma^2$,并设$\varepsilon_t$与$X_{t-1},X_{t-2},...$独立。系数$|\phi_1|<1$。更一般的定义中仅要求$\{\varepsilon_t\}$是零均值白噪声，不要求独立同分布。

这个模型与一元线性回归模型$Y_i=\phi_0+\phi_1x_i+\varepsilon_i$在某些方面类似，比如，$\varepsilon_t$都是起到误差或者扰动的作用。但是， 在自回归模型中，自变量$X_{t-1}$在时刻$t-1$时作为因变量，所以自回归模型中因变量和自变量不是两个变量而是同一个变量的不同时刻。回归模型的理论结果不能直接应用到自回归模型当中。

AR(1)模型也是马尔可夫 (Markov) 过程：$X_t$在$X_{t-1},X_{t-2},...$条件下的条件分布，只与$X_{t-1}$有关。已知$X_{t-1}$后，用$X_{t-1},X_{t-2},...$去预测$X_t$,与仅用$X_{t-1}$去预测的效果相同。这种性质称为**马氏性**。

条件期望和条件方差：

$$E(X_t|X_{t-1})=\phi_0+\phi_1X_{t-1},\quad\mathrm{Var}(X_t|X_{t-1})=\sigma^2$$

即在$X_t-1=x_{t-1}$已知后，$X_t$条件的条件分布是期望为$\phi_0+\phi_1x_{t-1}$,方差为$\sigma^2$的分布。可以证明：

$$\mathrm{Var}(X_t)=\frac{\sigma^2}{1-\phi_1^2}$$

因为$|\phi_1|<1$,所以$X_t$在$X_t-1=x_{t-1}$已知条件下的条件方差小于其无条件方差，也就是说用$X_t-1$的信息去预测$X_t$,可以使得$X_t$的波动减小，能够达到预测的效果。

AR(1)模型的推广是 AR$(p)$模型：

$$X_t=\phi_0+\phi_1X_{t-1}+\cdots+\phi_pX_{t-p}+\varepsilon_t$$

其中$\{\varepsilon_t\}$是零均值独立同分布白噪声序列，方差为$\sigma^2$,且$\varepsilon_t$与$X_t-1,X_{t-2},...$独立。系数$\phi_1,...,\phi_p$需要满足如下条件：方程

$$1-\phi_1z-\cdots-\phi_pz^p=0$$

的所有复根$z_*$都满足$|z_*|>1$,上述方程的左边的多项式称为 AR(p) 模型的**特征多项式**，特征多项式的所有复根称为**特征根**，对系数的条件称为“特征根都在单位圆外”。在有的教材中将特征多项式的根的倒数定义为特征根，在(R. S. Tsay, 2013) 中就是以倒数为特征根。对 AR(1) 就是要求$|\phi_1|<1.$

更一般的定义中仅要求$\{\varepsilon_t\}$是零均值白噪声，不要求独立同分布。

## 滞后算子

设$\{\xi_t,t\in\mathbb{Z}\}$为弱平稳时间序列或者常数列，定义如下的滞后算子$B$：

$$B\xi_t=\xi_{t-1},\quad B^j\xi_t=\xi_{t-j},\:j\in\mathbb{Z}$$

考虑复变函数$P(z)=\sum_{j=0}^\infty a_jz^j$,其中$\{a_j\}$为实数列，设$\sum_{j=0}^\infty|a_j|<\infty$ (称为系数**绝对可和**),有限阶多项式为$P(z)$的特例。定义：

$$P(B)\xi_t=\sum_{j=0}^\infty a_j\xi_{j-t}.$$

$P(B)$也称为一个(常系数时齐)线性滤波器，$P(B)\xi_t$是$\{\xi_t\}$序列的一个滑动平均变换。

设$Q(z)=\sum_{j=0}^\infty b_jz^j,\{b_j\}$为实数列，绝对可和，则$C(z)=P(z)Q(z)=\sum_{j=0}^\infty c_jz^j$,其中：

$$c_j=\sum\limits_{i=0}^ja_ib_{j-i},\:j=0,1,...$$

且$\{c_j\}$绝对可和，称数列$\{c_j\}$是数列$\{a_j\}$和数列$\{b_j\}$的**离散卷积**。对任意弱平稳列或者常数列$\{\xi_t\}$均有：

$$P(B)Q(B)\xi_t=Q(B)P(B)\xi_t=C(B)\xi_t,\:t\in\mathbb{Z}$$

若$\xi_t\equiv\xi$与$t$无关，则$B^j\xi=\xi$。比如，$B^j1=1,P(B)1=P(1)$。

令$D(z)=\frac{P(z)}{Q(z)}$,若$Q(z)\neq0$对任意满足$|z|\leq1$的复数$z$均成立，则$D(z)=\sum_{j=0}^\infty d_jz^j,\{d_j\}$绝对可和，且：

$$P(B)\xi_t=Q(B)D(B)\xi_t=D(B)Q(B)\xi_t,\:t\in\mathbb{Z}$$

## TODO: AR(1) 模型的性质

## TODO: AR(1) 模型的自相关函数

## TODO: AR(2) 模型的性质

#### TODO: 例子：美国的国民生产总值 (GNP) 经过季节调整后的季度增长率

## AR(p) 模型的性质

对于一般的AR( p) 模型，其 ACF 的性质以及序列的随机周期，也由其特征根决定。ACF 可以是单调衰减、震荡衰减、正负交替衰减、呈周期震荡衰减。在有复特征根根或者有接近-1的特征根时时间序列呈现出一定的随机周期变化。

由平稳性得：

$$\mu=\frac{\phi_0}{1-\phi_1-\cdots-\phi_p}$$

自相关函数 (ACF) 满足如下的递推(差分方程)：

$$\begin{matrix}(1-\phi_1B-\cdots-\phi_pB^p)\rho_j=0,&j=1,2,...\end{matrix}$$

AR$(p)$模型的平稳解是线性时间序列。

## 偏自相关函数

实际数据用 AR 模型建模时，阶数$p$是未知的，确定$p$的问题称为**定阶**。一般常用偏自相关函数和 AIC 准则。

设$X_1,...,X_n,Y$为随机变量：

$$L(Y|X_1,\dots,X_n)=\underset{\hat{Y}=b_0+b_1X_1+\dots+b_nX_n}{\operatorname*{argmin}}E(Y-\hat{Y})^2$$

称为用$X_1,...,X_n$对$Y$的最优线性预测。$Y-L(Y|X_1,...,X_n)$与$Z-L(Z|X_1,...,X_n)$的相关系数称为$Y$和$Z$
在扣除$X_1,...,X_n$影响后的**偏相关系数**。

对平稳线性时间序列，对$n=1,2,...$,有：

$$L(X_t|X_{t-1},...,X_{t-n})=\phi_{n0}+\phi_{n1}X_{t-1}+...+\phi_{nn}X_{t-n}$$

其中$\phi_{nj},j=0,1,...,n$与$t$无关。称$\phi_{nn}$为时间序列$\{X_t\}$的**偏自相关系数**，$\{\phi_{nn}\}$序列称为时间序列$\{X_t\}$的**偏自相关函数(PACF)**。

$\phi_{nn}$实际是$X_t$与$X_t-n$在扣除$X_t-2,...,X_t-n+1$的影响后的偏相关系数。$\phi_11$就是$\rho_1$。

$\phi_{nn}$用样本进行估计，得到的估计值$\hat{\phi}_{nn},n=1,2,...$称为**样本偏自相关函数**。

如果$\{X_t\}$服从如下 AR$(p)$模型：

$$X_t=\phi_0+\phi_1X_{t-1}+\cdots+\phi_pX_{t-p}+\varepsilon_t,\:\phi_p\neq0$$

这意味着用$X_{t-1},X_{t-2},...$的线性组合预测$X_t$时，只需要用到$X_t-1,...,X_{t-p}$,增加$X_{t-p-1},X_{t-p-2},...$不能改进预测。这意味着$\phi_{kk}=0,k>p$。这种性质叫做 AR 模型的偏自相关函数截尾性。

AR(p) 序列的样本偏自相关函数$\hat{\phi}_{kk}$满足如下性质：

- $T\to \infty$ 时$\hat{\phi}_pp\to\phi_p\neq0$。
- 对$k>p,\hat{\phi}_{kk}\to0(\hat{T}\to\infty)$。
- 对$k>p,\hat{\phi}_{kk}$渐近方差为$\frac1T$。

这样，可以用类似对 ACF 的白噪声检验那样给 PACF 图画出$\pm\frac2{\sqrt{T}}$的上下界限，以此判断 PACF 在哪里截尾。

#### 例子：CRSP 价值加权指数月度收益率

查看数据：

```{python}
{{< include _sample_crsp_1.py >}}
{{< include _sample_crsp_2.py >}}
```

绘制 ACF 图像：

```{python}
{{< include _sample_crsp_1.py >}}
{{< include _sample_crsp_3.py >}}
```

发现 ACF 到 $k = 21$ 还没有截尾，绘制 PACF 图：

```{python}
{{< include _sample_crsp_1.py >}}
{{< include _sample_crsp_4.py >}}
```

查看 PACF 图像，可以近似认为 $p = 3$，但实际上 PACF 在 $k = 17$ 处仍未截尾。

#### 例子：美国的国民生产总值 (GNP) 经过季节调整后的季度增长率

这是 [TODO: 例子：美国的国民生产总值 (GNP) 经过季节调整后的季度增长率] 的继续，判断美国 GNP 经过季节调整后的季度增长率的 $p$ 的取值。

绘制 ACF 图：
```{python}
{{< include _sample_gnp_1.py >}}
{{< include _sample_gnp_2.py >}}
```

ACF 图明显不截尾，绘制 PACF 图：

```{python}
{{< include _sample_gnp_1.py >}}
{{< include _sample_gnp_3.py >}}
```

PACF 虽然在 $k = 3, 9, 14, 16$ 等位置超出界限，但是超出不多，可考虑用 AR(3) 建模。

## 信息准则

信息准则是统计建模中常用的模型比较工具，其基本思想是模型拟合数据的拟合优度与模型简单化的折衷。
AIC 准则(Akaike's Information Criterion):

$$\mathrm{AIC}=-\frac{2}{T}\ln(\text{似然函数值})+\frac{2}{T}(\text{参数个数})$$

其中似然函数值是在参数最大似然估计处的似然函数值。当模型为高斯AR( p) ,即$\{\epsilon_t\}$是独立同 N$(0,\sigma^2)$序列时的AR$(p)$模型时，AIC 公式为：

$$\mathrm{AIC}(k)=\ln\tilde{\sigma}_k^2+\frac{2k}{T}$$

其中$k$是模型的阶，$\tilde{\sigma}_k^2$是阶为$k$的条件下$\varepsilon_t$的方差的最大似然估计。$\ln\tilde{\sigma}_k^2$代表了模型对数据的拟合优劣，此值越大拟合越差；$\frac{2k}{r}$是对模型复杂程度的惩罚，此值越大，模型越复杂，稳定性越差，对未来的情况的适应性也越差。在某个范围内取$k$使得 AIC$(k)$最小，就达成了拟合优度与模型简单程度的折衷。

另一个常用的信息准则是 BIC 准则 (Bayesian Information Criterion),高斯 AR 模型为：

$$\mathrm{BIC}(k)=\ln\tilde{\sigma}_k^2+\frac{k\ln T}{T}$$

BIC 倾向于取比 AIC 更低阶的模型。

可以取 $k = 0, 1, \cdots, P_0$ 计算 AIC 或 BIC，去最小值点的 $k$。$P_0$ 可以取为 $10 \log_{10} T$。

## AR 模型的参数估计方法

AR 模型有多种估计方法，比如，用普通线性回归的最小二乘法估计，假设正态分布用最大似然估计，Yule-Walken
递推计算，Burg 递推计算，等等。

设$\phi_i$的估计为$\hat{\phi}_i$,则拟合值为：

$$\hat{x}_t=\hat{\phi}_0+\hat{\phi}_1x_{t-1}+\cdots+\hat{\phi}_px_{t-p},\:t=p+1,...,T$$

残差为：

$$e_t=x_t-\hat{x}_t,\:t=p+1,...,T$$

相应的新息方差$\sigma^2=$Var$(\varepsilon_t)$的估计为：

$$\hat{\sigma}^2=\frac{1}{T-2p-1}\sum\limits_{t=p+1}^Te_t^2$$

如果使用高斯条件最大似然估计(认为$x_1,...,x_p$固定),则$\hat{\phi}_i$估计不变，但是新息方差得估计变成了：

$$\tilde{\sigma}^2=\frac{1}{T-p}\sum_{t=p+1}^Te_t^2=\frac{T-2p-1}{T-p}\sum_{t=p+1}^Te_t^2$$

## TODO：AR 模型拟合优度指标

## TODO：用估计的 AR 模型进行预测
